[package]
name = "nix-rust"
version = "0.1.0"
authors = ["Eelco Dolstra <edolstra@gmail.com>"]
edition = "2018"

[lib]
name = "nixrust"
crate-type = ["cdylib"]

[dependencies]
tar = "0.4"
libc = "0.2"
futures-preview = { version = "=0.3.0-alpha.18", features = ["compat"] }
#hyper = "0.12"
reqwest = { version = "0.9", default-features = false, features = ["rustls-tls"] }
http = "0.1"
tokio = { version = "0.1", default-features = false }
